package io.linuxtips.funcionariotdd.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "funcionarios")
public class Funcionario{

        private String id;

        private  String nome;

        private Double remuneracao;

        public Funcionario(String id, String nome, Double remuneracao) {
                this.id = id;
                this.nome = nome;
                this.remuneracao = remuneracao;
        }

        @DynamoDBHashKey(attributeName = "id")
        @DynamoDBAutoGeneratedKey
        public String getId(){
                return this.id;
        }


        @DynamoDBAttribute(attributeName = "nome")
        public String getNome(){
                return this.nome;
        }


        @DynamoDBAttribute(attributeName = "remuneracao")
        public Double getRemuneracao(){
                return this.remuneracao;
        }

        @Override
        public String toString(){
                return "{id="+id+",nome="+nome+",remuneracao="+remuneracao+"}";
        }
}
